"use client";

import { useEffect, useMemo, useState } from "react";
import { addMonths, eachDayOfInterval, endOfMonth, endOfWeek, format, isSameMonth, startOfMonth, startOfWeek, subMonths } from "date-fns";
import { ru } from "date-fns/locale";
import { Award, CalendarDays, ChevronDown, ChevronLeft, ChevronRight, CircleAlert, Filter, List, RotateCcw, Search, Trophy, X } from "lucide-react";
import { olympiads, sourceRuleCount } from "@/data/olympiads";
import type { BenefitType, Exam, Olympiad, OlympiadStage } from "@/data/types";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";

type Filters = { q: string; subject: "all" | Exam; benefit: "all" | BenefitType; eligibility: "all" | "winner" | "all_medalists"; level: "all" | "1" | "2" | "3" | "unknown"; stage: "all" | OlympiadStage["type"] | "unknown"; period: "all" | "month" | "30" | "custom"; from: string; to: string };
type View = "list" | "calendar";
type Sort = "date" | "name" | "bvi" | "complete";

const defaults: Filters = { q: "", subject: "all", benefit: "all", eligibility: "all", level: "all", stage: "all", period: "all", from: "", to: "" };
const subjectOptions: { value: Filters["subject"]; label: string }[] = [{ value: "all", label: "Все" }, { value: "информатика", label: "Информатика" }, { value: "математика", label: "Математика" }, { value: "русский язык", label: "Русский язык" }];
const benefitOptions: { value: Filters["benefit"]; label: string }[] = [{ value: "all", label: "Все" }, { value: "BVI", label: "БВИ" }, { value: "100_POINTS", label: "100 баллов" }];

function parseSearchParams(input: Record<string, string | string[] | undefined>): { filters: Filters; view: View; sort: Sort } {
  const p = new URLSearchParams();
  Object.entries(input).forEach(([key, value]) => { if (typeof value === "string") p.set(key, value); });
  return { filters: { q: p.get("q") ?? "", subject: (p.get("subject") as Filters["subject"]) ?? "all", benefit: (p.get("benefit") as Filters["benefit"]) ?? "all", eligibility: (p.get("eligibility") as Filters["eligibility"]) ?? "all", level: (p.get("level") as Filters["level"]) ?? "all", stage: (p.get("stage") as Filters["stage"]) ?? "all", period: (p.get("period") as Filters["period"]) ?? "all", from: p.get("from") ?? "", to: p.get("to") ?? "" }, view: p.get("view") === "calendar" ? "calendar" : "list", sort: (p.get("sort") as Sort) ?? "name" };
}

function PageHeader() {
  return <header className="border-b bg-card"><div className="mx-auto flex max-w-7xl flex-col gap-2 px-4 py-6 sm:px-6 lg:px-8"><div className="flex items-center gap-3"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Trophy className="size-5" /></div><div><h1 className="text-xl font-semibold tracking-tight sm:text-2xl">Олимпиады для ПМИ ВШЭ</h1><p className="text-sm text-muted-foreground">Москва · поступление в 2026 году</p></div></div><p className="ml-0 text-sm text-muted-foreground sm:ml-[3.25rem]">Найдите олимпиады по предмету, льготе и этапу сезона</p></div></header>;
}

function AdmissionRequirements() {
  return <section aria-labelledby="requirements-title" className="rounded-xl border bg-card p-4 sm:p-5"><div className="flex items-start gap-3"><div className="mt-0.5 flex size-8 shrink-0 items-center justify-center rounded-lg bg-secondary text-primary"><Award className="size-4" /></div><div className="min-w-0 flex-1"><h2 id="requirements-title" className="font-semibold">Как подтвердить льготу</h2><div className="mt-3 grid gap-2 text-sm sm:grid-cols-4"><Requirement subject="Информатика" score="от 90" /><Requirement subject="Математика" score="от 85" /><Requirement subject="Русский язык" score="от 75" /><Requirement subject="Диплом" score="получен в 11 классе" /></div><p className="mt-3 flex gap-2 text-xs leading-5 text-muted-foreground"><CircleAlert className="mt-0.5 size-4 shrink-0" />Профиль олимпиады должен входить в официальный перечень в год получения диплома.</p></div></div></section>;
}
function Requirement({ subject, score }: { subject: string; score: string }) { return <div className="rounded-lg bg-muted px-3 py-2"><span className="text-muted-foreground">{subject}</span><strong className="ml-1 font-semibold">{score}</strong></div>; }

function Segment<T extends string>({ label, value, options, onChange }: { label: string; value: T; options: { value: T; label: string }[]; onChange: (value: T) => void }) {
  return <fieldset><legend className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</legend><div className="flex flex-wrap gap-1 rounded-lg bg-muted p-1">{options.map((option) => <button key={option.value} type="button" onClick={() => onChange(option.value)} aria-pressed={value === option.value} className={cn("min-h-9 flex-1 rounded-md px-3 text-sm font-medium transition-colors", value === option.value ? "bg-card text-foreground shadow-sm" : "text-muted-foreground hover:text-foreground")}>{option.label}</button>)}</div></fieldset>;
}

function FilterFields({ filters, setFilters }: { filters: Filters; setFilters: (next: Filters) => void }) {
  const set = <K extends keyof Filters>(key: K, value: Filters[K]) => setFilters({ ...filters, [key]: value });
  return <div className="grid gap-5"><label className="relative block"><span className="mb-2 block text-xs font-semibold uppercase tracking-wide text-muted-foreground">Название</span><Search className="absolute bottom-2.5 left-3 size-4 text-muted-foreground" /><input value={filters.q} onChange={(e) => set("q", e.target.value)} placeholder="Поиск олимпиады" className="h-10 w-full rounded-lg border bg-card pl-9 pr-3 text-sm" /></label><Segment label="Предмет подтверждения" value={filters.subject} options={subjectOptions} onChange={(v) => set("subject", v)} /><Segment label="Льгота" value={filters.benefit} options={benefitOptions} onChange={(v) => set("benefit", v)} /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><SelectField label="Право" value={filters.eligibility} onChange={(v) => set("eligibility", v as Filters["eligibility"])} options={[["all", "Все"], ["winner", "Только победителям"], ["all_medalists", "Победителям и призёрам"]]} /><SelectField label="Уровень РСОШ" value={filters.level} onChange={(v) => set("level", v as Filters["level"])} options={[["all", "Все"], ["1", "I"], ["2", "II"], ["3", "III"], ["unknown", "Не указан"]]} /><SelectField label="Этап" value={filters.stage} onChange={(v) => set("stage", v as Filters["stage"])} options={[["all", "Все"], ["registration", "Регистрация"], ["qualification", "Отборочный"], ["final", "Заключительный"], ["results", "Результаты"], ["unknown", "Данные не указаны"]]} /><SelectField label="Период" value={filters.period} onChange={(v) => set("period", v as Filters["period"])} options={[["all", "Весь сезон"], ["month", "Текущий месяц"], ["30", "Следующие 30 дней"], ["custom", "Свой диапазон"]]} /></div>{filters.period === "custom" && <div className="grid grid-cols-2 gap-3"><label className="text-sm">С даты<input type="date" value={filters.from} onChange={(e) => set("from", e.target.value)} className="mt-1 h-10 w-full rounded-lg border bg-card px-3" /></label><label className="text-sm">По дату<input type="date" value={filters.to} onChange={(e) => set("to", e.target.value)} className="mt-1 h-10 w-full rounded-lg border bg-card px-3" /></label></div>}</div>;
}
function SelectField({ label, value, options, onChange }: { label: string; value: string; options: [string, string][]; onChange: (value: string) => void }) { return <label><span className="mb-2 block text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</span><select value={value} onChange={(e) => onChange(e.target.value)} className="h-10 w-full rounded-lg border bg-card px-3 text-sm">{options.map(([v, l]) => <option value={v} key={v}>{l}</option>)}</select></label>; }

function OlympiadFilters({ filters, setFilters }: { filters: Filters; setFilters: (next: Filters) => void }) {
  return <><div className="hidden rounded-xl border bg-card p-5 md:block"><FilterFields filters={filters} setFilters={setFilters} /></div><div className="md:hidden"><Sheet><SheetTrigger asChild><Button variant="outline" className="w-full"><Filter className="size-4" />Открыть фильтры</Button></SheetTrigger><SheetContent><FilterFields filters={filters} setFilters={setFilters} /></SheetContent></Sheet></div></>;
}

const filterLabels: Record<string, string> = { subject: "Предмет", benefit: "Льгота", eligibility: "Право", level: "Уровень", stage: "Этап", period: "Период" };
const valueLabels: Record<string, string> = { информатика: "Информатика", математика: "Математика", "русский язык": "Русский язык", BVI: "БВИ", "100_POINTS": "100 баллов", winner: "Только победителям", all_medalists: "Победителям и призёрам", unknown: "Не указано", "1": "I", "2": "II", "3": "III", registration: "Регистрация", qualification: "Отборочный", final: "Заключительный", results: "Результаты", month: "Текущий месяц", "30": "Следующие 30 дней", custom: "Свой диапазон" };
function ActiveFilterChips({ filters, setFilters }: { filters: Filters; setFilters: (next: Filters) => void }) {
  const active = Object.entries(filters).filter(([key, value]) => value && value !== "all" && key !== "from" && key !== "to");
  if (!active.length) return null;
  return <div className="flex flex-wrap gap-2" aria-label="Активные фильтры">{active.map(([key, value]) => <button key={key} onClick={() => setFilters({ ...filters, [key]: key === "q" ? "" : "all" })} className="inline-flex min-h-8 items-center gap-1 rounded-full border bg-card px-3 text-xs font-medium hover:border-primary"><span className="text-muted-foreground">{key === "q" ? "Поиск" : filterLabels[key]}:</span> {key === "q" ? `«${value}»` : valueLabels[value]} <X className="size-3" /></button>)}</div>;
}

function ViewToggle({ view, setView }: { view: View; setView: (view: View) => void }) { return <div className="flex rounded-lg border bg-card p-1" aria-label="Вид результатов">{([['list', List, 'Список'], ['calendar', CalendarDays, 'Календарь']] as const).map(([value, Icon, label]) => <button key={value} onClick={() => setView(value)} aria-pressed={view === value} className={cn("flex h-8 items-center gap-2 rounded-md px-3 text-sm font-medium", view === value ? "bg-secondary text-primary" : "text-muted-foreground hover:text-foreground")}><Icon className="size-4" />{label}</button>)}</div>; }

function benefitLabel(type: BenefitType) { return type === "BVI" ? "БВИ" : "100 баллов"; }
function statusLabel(status: "WINNER" | "WINNER_OR_PRIZEWINNER") { return status === "WINNER" ? "Только победителям" : "Победителям и призёрам"; }
function BenefitBadge({ type }: { type: BenefitType }) { return <span className={cn("inline-flex rounded-md px-2 py-1 text-xs font-semibold", type === "BVI" ? "bg-primary text-primary-foreground" : "bg-[#e7eff9] text-[#27537f]")}>{benefitLabel(type)}</span>; }

function ProfileBenefitTable({ olympiad }: { olympiad: Olympiad }) {
  const rules = olympiad.profiles.flatMap((profile) => profile.benefits.map((benefit) => ({ profile, benefit })));
  return <div className="border-t bg-[#fbfcfc] p-4 sm:p-5"><div className="overflow-hidden md:rounded-lg md:border"><table className="profile-table w-full text-left text-sm"><thead className="bg-muted text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-3 py-3">Профиль</th><th className="px-3 py-3">Предмет олимпиады</th><th className="px-3 py-3">Подтверждение</th><th className="px-3 py-3 text-right">Порог</th><th className="px-3 py-3">Льгота</th><th className="px-3 py-3">Кому</th></tr></thead><tbody className="divide-y">{rules.map(({ profile, benefit }, i) => <tr key={`${profile.id}-${i}`} className="bg-card align-top"><td data-label="Профиль" className="px-3 py-3 font-medium">{profile.profile}</td><td data-label="Предмет" className="max-w-64 px-3 py-3 text-muted-foreground">{profile.olympiadSubject}</td><td data-label="ЕГЭ" className="px-3 py-3">{profile.confirmationExam}</td><td data-label="Порог" className="px-3 py-3 text-right font-semibold md:text-right">{profile.confirmationThreshold}</td><td data-label="Льгота" className="px-3 py-3"><BenefitBadge type={benefit.type} /></td><td data-label="Кому" className="px-3 py-3">{statusLabel(benefit.eligibleStatus)}</td></tr>)}</tbody></table></div><p className="mt-3 text-xs text-muted-foreground">Уровень РСОШ, даты, этапы и официальный сайт: <span className="font-medium text-foreground">данные уточняются</span></p></div>;
}

function OlympiadCard({ olympiad }: { olympiad: Olympiad }) {
  const hasBvi = olympiad.profiles.some((p) => p.benefits.some((b) => b.type === "BVI"));
  const bestRules = olympiad.profiles.flatMap((p) => p.benefits).filter((b) => b.type === (hasBvi ? "BVI" : "100_POINTS"));
  const allMedalists = bestRules.some((b) => b.eligibleStatus === "WINNER_OR_PRIZEWINNER");
  const exams = [...new Set(olympiad.profiles.map((p) => p.confirmationExam))];
  const profiles = [...new Set(olympiad.profiles.map((p) => p.profile))];
  return <details className="group overflow-hidden rounded-xl border bg-card transition-colors open:border-[#b8ccc5]"><summary className="grid min-h-36 cursor-pointer list-none gap-4 p-4 hover:bg-[#fbfcfc] sm:grid-cols-[1fr_auto] sm:p-5"><div><div className="mb-2 flex flex-wrap items-center gap-2"><BenefitBadge type={hasBvi ? "BVI" : "100_POINTS"} /><span className="text-xs font-medium text-muted-foreground">{allMedalists ? "Победителям и призёрам" : "Только победителям"}</span></div><h3 className="max-w-3xl text-base font-semibold leading-snug sm:text-lg">{olympiad.name}</h3><div className="mt-3 flex flex-wrap gap-2 text-xs">{exams.map((exam) => <span key={exam} className="rounded-full bg-muted px-2.5 py-1 capitalize">{exam}</span>)}<span className="text-muted-foreground">{profiles.length} {profiles.length === 1 ? "профиль" : profiles.length < 5 ? "профиля" : "профилей"}</span></div></div><div className="flex items-end justify-between gap-4 sm:w-48 sm:flex-col sm:items-end"><div className="text-left sm:text-right"><p className="text-xs text-muted-foreground">Ближайший этап</p><p className="mt-1 text-sm font-medium">Даты уточняются</p></div><span className="flex items-center gap-1 text-xs font-semibold text-primary">Все условия <ChevronDown className="size-4 transition-transform group-open:rotate-180" /></span></div></summary><ProfileBenefitTable olympiad={olympiad} /></details>;
}
function EmptyState({ onReset }: { onReset: () => void }) { return <div className="rounded-xl border border-dashed bg-card px-5 py-14 text-center"><Search className="mx-auto size-8 text-muted-foreground" /><h3 className="mt-4 font-semibold">Ничего не найдено</h3><p className="mx-auto mt-1 max-w-md text-sm text-muted-foreground">Попробуйте изменить предмет, льготу или другие условия поиска.</p><Button variant="outline" className="mt-5" onClick={onReset}><RotateCcw className="size-4" />Сбросить фильтры</Button></div>; }
function OlympiadList({ items, onReset }: { items: Olympiad[]; onReset: () => void }) { return items.length ? <div className="grid gap-3">{items.map((item) => <OlympiadCard key={item.id} olympiad={item} />)}</div> : <EmptyState onReset={onReset} />; }

function OlympiadCalendar({ onList }: { onList: () => void }) {
  const [month, setMonth] = useState(new Date());
  const days = eachDayOfInterval({ start: startOfWeek(startOfMonth(month), { weekStartsOn: 1 }), end: endOfWeek(endOfMonth(month), { weekStartsOn: 1 }) });
  return <div className="rounded-xl border bg-card"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><p className="text-xs font-medium text-muted-foreground">Олимпиадный сезон</p><h2 className="text-lg font-semibold capitalize">{format(month, "LLLL yyyy", { locale: ru })}</h2></div><div className="flex items-center gap-1"><Button variant="outline" size="sm" onClick={() => setMonth(new Date())}>Сегодня</Button><Button variant="ghost" size="icon" aria-label="Предыдущий месяц" onClick={() => setMonth(subMonths(month, 1))}><ChevronLeft className="size-4" /></Button><Button variant="ghost" size="icon" aria-label="Следующий месяц" onClick={() => setMonth(addMonths(month, 1))}><ChevronRight className="size-4" /></Button></div></div><div className="p-3 sm:p-5"><div className="grid grid-cols-7 text-center text-xs font-medium text-muted-foreground">{["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"].map((d) => <div key={d} className="py-2">{d}</div>)}</div><div className="grid grid-cols-7 overflow-hidden rounded-lg border border-r-0 border-b-0">{days.map((day) => <div key={day.toISOString()} className={cn("aspect-square border-b border-r p-1.5 text-right text-xs sm:min-h-20 sm:aspect-auto", !isSameMonth(day, month) && "bg-muted/50 text-muted-foreground")}>{format(day, "d")}</div>)}</div><div className="mx-auto max-w-xl px-3 py-10 text-center"><CalendarDays className="mx-auto size-8 text-muted-foreground" /><h3 className="mt-4 font-semibold">Даты этапов ещё не добавлены</h3><p className="mt-1 text-sm text-muted-foreground">Олимпиады доступны в режиме списка. Мы не размещаем события в календаре без подтверждённых дат.</p><Button className="mt-5" onClick={onList}><List className="size-4" />Перейти к списку</Button></div></div></div>;
}

function matches(o: Olympiad, f: Filters) {
  if (f.q && !o.name.toLocaleLowerCase("ru").includes(f.q.toLocaleLowerCase("ru"))) return false;
  if (f.subject !== "all" && !o.profiles.some((p) => p.confirmationExam === f.subject)) return false;
  if (f.benefit !== "all" && !o.profiles.some((p) => p.benefits.some((b) => b.type === f.benefit))) return false;
  if (f.eligibility === "winner" && !o.profiles.some((p) => p.benefits.some((b) => b.eligibleStatus === "WINNER"))) return false;
  if (f.eligibility === "all_medalists" && !o.profiles.some((p) => p.benefits.some((b) => b.eligibleStatus === "WINNER_OR_PRIZEWINNER"))) return false;
  if (f.level !== "all" && (f.level === "unknown" ? o.federalLevel !== undefined : o.federalLevel !== Number(f.level))) return false;
  if (f.stage !== "all" && (f.stage === "unknown" ? !!o.stages?.length : !o.stages?.some((s) => s.type === f.stage))) return false;
  if (f.period !== "all" && !o.stages?.some((s) => s.startDate)) return false;
  return true;
}

export function OlympiadExplorer({ initialSearchParams }: { initialSearchParams: Record<string, string | string[] | undefined> }) {
  const initial = parseSearchParams(initialSearchParams);
  const [filters, setFilters] = useState<Filters>(initial.filters); const [view, setView] = useState<View>(initial.view); const [sort, setSort] = useState<Sort>(initial.sort);
  useEffect(() => { const p = new URLSearchParams(); Object.entries(filters).forEach(([k, v]) => { if (v && v !== "all") p.set(k, v); }); if (view !== "list") p.set("view", view); if (sort !== "name") p.set("sort", sort); const query = p.toString(); window.history.replaceState(null, "", query ? `?${query}` : window.location.pathname); }, [filters, view, sort]);
  const items = useMemo(() => olympiads.filter((o) => matches(o, filters)).sort((a, b) => { if (sort === "bvi") return Number(!b.profiles.some((p) => p.benefits.some((x) => x.type === "BVI"))) - Number(!a.profiles.some((p) => p.benefits.some((x) => x.type === "BVI"))) || a.name.localeCompare(b.name, "ru"); if (sort === "complete") return Number(!b.stages?.length) - Number(!a.stages?.length) || a.name.localeCompare(b.name, "ru"); return a.name.localeCompare(b.name, "ru"); }), [filters, sort]);
  const reset = () => { setFilters(defaults); setSort("name"); };
  return <><PageHeader /><main className="mx-auto max-w-7xl space-y-5 px-4 py-5 sm:px-6 sm:py-7 lg:px-8"><AdmissionRequirements /><OlympiadFilters filters={filters} setFilters={setFilters} /><div className="flex flex-col gap-3"><ActiveFilterChips filters={filters} setFilters={setFilters} /><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">Найдено: {items.length}</p><p className="text-xs text-muted-foreground">{sourceRuleCount} правил в исходных данных</p></div><div className="flex flex-1 flex-wrap justify-end gap-2">{view === "list" && <select value={sort} onChange={(e) => setSort(e.target.value as Sort)} aria-label="Сортировка" className="h-10 max-w-64 rounded-lg border bg-card px-3 text-sm"><option value="date">По ближайшей дате</option><option value="name">По названию</option><option value="bvi">Сначала БВИ</option><option value="complete">Сначала с полными данными</option></select>}<Button variant="ghost" onClick={reset} className="hidden sm:inline-flex"><RotateCcw className="size-4" />Сбросить</Button><ViewToggle view={view} setView={setView} /></div></div></div>{view === "list" ? <OlympiadList items={items} onReset={reset} /> : <OlympiadCalendar onList={() => setView("list")} />}<footer className="border-t py-5 text-xs leading-5 text-muted-foreground"><p>Источник: приложение 2 НИУ ВШЭ для программы «Прикладная математика и информатика», Москва, приём 2026.</p><p>Отсутствующие сведения не интерпретируются как отсутствие этапа или льготы.</p></footer></main></>;
}
